config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users

  resources :users, only: [:index, :show] do
    resources :items, only: [:create, :update, :new, :destroy]
  end

  get "welcome/index"

  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :items, dependent: :destroy
  # Include default devise modules. Others available are:
  #  :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(users)
    user_path(current_user.id)
  end

  def destroy_expired_items
    Item.where("created_at <= ?", Time.now - 7.days).destroy_all
  end


  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password) }
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  def create
    @item = Item.new
    @item.user = User.find(params[:user_id])
    @item.assign_attributes(post_params)

    if @item.save
      render json: {data: render_to_string(:partial => 'item', layout: false, locals: {item: @item})}
    else
      render json: { status: 'failed'}, status: 400
    end

  end

  def update
    @item = Item.find(params[:id])

    if @item.update_attributes(post_params)
      render json: {status: 'success'}, status: 200
    else
      render json: {status: 'failed'}, status: 400
    end
  end

  def destroy
    @user = User.find(params[:user_id])
    @item = Item.find(params[:id])

    @item.destroy
  end

  private
  def post_params
    params.require(:item).permit(:user, :name)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :destroy_expired_items

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end


end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def active(user)
    if user.items.any?
      time_ago_in_words(user.items.last.created_at)
    elsif user.last_sign_in_at
      time_ago_in_words(user.last_sign_in_at)
    else
      time_ago_in_words(user.created_at)
    end
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/items/_form.html.erb
<% if current_user&.id == params[:user_id].to_i %>
  <tr>
    <td class="col-xs-8"><input type="text" class="new_item" autocomplete="off" autofocus /></td>
    <td>7 days</td>
    <td><%= link_to "", user_path(params[:user_id]), method: :get, class: 'glyphicon glyphicon-ok', remote: true %></a></td>
  </tr>
<% end %>

app/views/items/_item.html.erb
<tr>
  <% if current_user&.id == item.user_id %>
    <td class="col-xs-9"><%= text_field(:item, :name, id: item.id, class: :item_name, value: item.name, autocomplete: :off) %></td>
    <td class="col-xs-2"><%= distance_of_time_in_words(Time.now - 7.days, item.created_at) %></td>
    <td class="col-xs-1"><%= link_to "", user_item_path(item.user_id, item.id), method: :delete, class: 'glyphicon glyphicon-ok', remote: true %></td>
  <% else %>
    <td class="col-xs-10"><%= text_field(:item, :name, id: item.id, class: :item_name, value: item.name, autocomplete: :off, readonly: true) %></td>
    <td><%= distance_of_time_in_words(Time.now - 7.days, item.created_at) %></td>
  <% end %>
</tr>

app/views/items/destroy.js.erb
$('table tbody').find('#<%= params[:id] %>').parent().parent().remove();

app/views/items/new.js.erb
$('.new_item').parent().parent().remove();
$('table tbody').append("<%= escape_javascript render(:partial => 'form') %>");
postNewItem();

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Driven</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <ul class="nav nav-tabs">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "All Users", users_path %></li>
        <div class="pull-right user-info">
          <% if user_signed_in? %>
            <%= link_to current_user.email, edit_user_registration_path, :class => 'navbar-link' %> - <%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
          <% else %>
            <%= link_to "Sign In", new_user_session_path, :class => 'navbar-link'  %>
          <% end %>
        </div>
      </ul>
      <%= yield %>
    </div>
  </body>
</html>

app/views/users/index.html.erb
<br>
<h1>All Users</h1>
<br>
<% @users.each do |user| %>
  <div class="media">
    <div class="media-body">
      <h4 class="media-heading">
        <%= link_to user.name, user_path(user) %>
      </h4>
      <small>
        Last active <%= active(user) %> ago <br>
        <%= user.items.count %> todos
      </small>
    </div>
  </div>
<% end %>

app/views/users/show.html.erb
<br><br>
<% if current_user&.id == @user.id %>
  <h1 class="text-center">My todos</h1>
<% else %>
  <h1 class="text-center"><%= @user.name %>'s todos</h1>
<% end %>
<br>
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <table class="table table-bordered table-striped">
      <thead>
        <tr>
          <th class="col-xs-9">Description</th>
          <th class="col-xs-2">Expires in</th>
          <% if current_user&.id == params[:id].to_i %>
            <th>Complete</th>
          <% end %>
        </tr>
      </thead>
      <tbody>
        <% @user.items.each do |item| %>
          <%= render partial: 'items/item', locals: { item: item } %>
        <% end %>
        <%= render partial: 'items/form' %>
      </tbody>
    </table>
    <% if current_user&.id == params[:id].to_i %>
      <%= button_to "Add New Todo", new_user_item_path(@user), method: :get, remote: true, class: :center %>
    <% end %>
  </div>
</div>

<script>
  editOrDeleteItem($(".item_name"));
</script>

app/views/welcome/about.html.erb
<h1>Welcome#about</h1>
<p>Driven is a personal project</p>

app/views/welcome/index.html.erb
<br>
<div class="jumbotron">
  <h1>Driven</h1>
  <p>Driven is self-destructing to-do list to keep you focused on the things that really matter.</p>
  <% if user_signed_in? %>
    <%= link_to "User Profile", user_path(current_user.id), :class => "btn-md btn btn-primary"  %>
  <% else %>
  <p>
    <%= link_to "Sign In", new_user_session_path, class: 'btn btn-primary' %> or
    <%= link_to "Sign Up", new_user_registration_path, class: 'btn btn-primary' %> today!
  </p>
  <% end %>

</div>

<div class="row">
  <div class="col-md-4">
    <h2>Solves world hunger</h2>
    <p>Driven will deliver food and water to those in need, all over the world.</p>
  </div>
  <div class="col-md-4">
    <h2>Eliminates poverty</h2>
    <p>Driven will deliver money and education to those in need, all over the world.</p>
  </div>
  <div class="col-md-4">
    <h2>Makes you better looking</h2>
    <p>Driven will make you better looking: it's scientifically proven to make men look like Ryan Gosling and women look like Shakira.</p>
  </div>